logging:
  file_path: "logs/orchestrator.log"
  level: "INFO"

database:
  url: "data/tasks.db"

tasks:
  - name: "random_commits"
    module: "random-commits"
    class: "RandomCommits"
    schedule: "*/15 * * * *"
    enabled: true
    config: {}
 